<BoxLayoutH@MDBoxLayout>:
    orientation: "horizontal"

<BoxLayoutV@MDBoxLayout>:
    orientation: "vertical"

<Tile>:
    fit_mode: "contain"

<Player>:
    fit_mode: "contain"

<GameField>:
    canvas.before:
        StencilPush
        Rectangle:
            size: self.size
            pos: self.pos
        StencilUse

    canvas.after:
        StencilUnUse
        Rectangle:
            size: self.size
            pos: self.pos
        StencilPop
